language: node_js
node_js:
  - 6
branches:
  only:
    - master
script:
  - cd functions
  - npm install
  - npm run lint
  - npm run test
  - cd ..
deploy:
  provider: firebase
  token:
    secure: IKRWPkvHSIMup3Qj689dAMFY0YT1V9mOViaF4DgdyNB/ZEgLUzxkYGNfZj0GHXGfRzbRuYp37S2NEeOqTqjJFYXdoILuFMSBz9deygIrjh20BIO+CEj4P2BrjjNjHbZczYFKygveMy0cntcJAWhGERlgVWK6iXh+I6AIPxEC5Xiu9w5jdbFkvm1i7Ms/6vpuYgL51Cv7MOFTX7HW6YmElAfo0x6V2Fr3eqIOQt3p3ldtyKP/2r9tgqUt2pPiDTSm8AVQ2znav2lcEPVQXxZYDJ+xA0dPCevjUi52CGBYCKMT+vKRiCmhQnbgU5jC3WSVpNBs3s63Q77+ZpYNYf3nYpKmxeG5ighLkRHhxEp3SuaxZDyYq6FPMd2BjI2G3f4M1oseSjuIhW1fuWk0lWzQr6J4IuaqhM+nT+YIcv8HZd3GZo9fYkAwLyMNmzpbqta6r6/HpBHak8he568o2X8+MgOYCjwW0cKS01C/Uj185thWqx3OYUs6IWM13TLiXieNtvZ73+xYMxInwtzptI/kv/MqtWY50yO6/X7CXiIg9vSSyh91IkRqp01lbrVrdAQXZBx42h7OJrOSkJiNn01Tuc/0dOSQ8BrYuG7SZDfYaQl4D/VL55pHFul62aa0rKrDd08C2LTeLe4qpF3nKWA6oOI3amRh9sJ54bpyqFCokc0=
  skip_cleanup: true
