language: node_js
node_js:
  - 6
branches:
  only:
    - master
script:
  - cd functions
  - npm install
  - npm run lint
  - npm run test
  - cd ..
deploy:
  provider: firebase
  token:
    secure: N5+o+HGrXKMibWargDvoCZ9D7BfqELAO7z1n7l59oEDc04ZgZspCr4SaNAgPHgIwmeiC6RZ+Gmcgj71eRpBhsbqpzT4krT4IRH90zfdjofyH9iplWmKEogyZvAHp7YJ9FXb9ECc3vuSAS0pKrrXqN7FyYbKLI6vwO46VZAWPSpdfogHsGYzwPcfdjy1UyxHxQp5FsM3Lesp7ky3w0RC6lXt/z9ISK5O9SSbryvqa2Di9fU/Po5rmvc6JcWI/ZwIvsL/2K4gSofrAzqLQcxe/WlOkmkYrvIrYEkSRMz/3eNDOOot5WFyYvQh+bW2KvYDjlPztRbk3tWI+a7s3xvRnvLXBRJ4j1KFZAAwGM/zcplHz0to4pFDHZZdvYROMUTv2jFMiCmFHnIjANVoxgh31ZN3lg/UdydKmDftEtYGFfzlZoxx3o/vDhMCX2nZ5+CD3/55tEDGrceSNfqPeDVZMoW8T+2lkmif98tMaPtl+ZDtzWTxyRTOCftQnPLM/z7M1qG6h2DphfEsckqduP3MnUv9YLaf/MAGnM4OGViddDyKsJVV5l3GG7eRifgJKtx7TVM8KPmzoLHR7d1dne7Nl8bSrxuWj0iHV+4NklnGFy2n/EGop9hGoNbZ2BqvFRaKcr1bjuVxefZTxaIQbUgv+2kI6V/ySrztWIgoFz/WmhVc=
  skip_cleanup: true
