language: node_js
node_js:
  - 6 # Maintenance
  - 8 # Active
  - 10 # Current release

branches:
  only:
    - master
    - next

script:
  - cd functions
  - npm run lint

deploy:
  provider: firebase
  token:
    secure: nT6XL8M9Hx9J8/hM718iGfAHGyZV35Rl1eTrPo6vJuNzuJlZnVEnVjw6tN4S+yBu20cqeA+e46m2qo9H+Fl4Df8PHaSR+SDSmBg2hWtZAFjSqqx4S3gg8lL7gF5AMztsFEbzUao/POOCUVPwpgs/7rZfo1uiQyCoD5geEhvqXecEMFI0ywzC5JM99Sa8X/ie7uzCp9ofC9oTgODbhjtG4aL5u+hza4YP4vWz/KzejuuwZ1+wDldhuHTIC6NPM70vF0gLqU1pa4y/6pADiG578Q8qlGWePZWukuyEjS0AV9+5OuqodIEJAe1rE6mCmkktQDsj4gCxUFkAyI4WLGwu+u85rMY0BWLvnIDVsnOHMhQMmP/I5FNRwyk2aGNl1w2oDk4wsP3PRoRhUgMJkBIfcRguygfn86FYKESaOso4iUQgknYZMDj1Zl+oRkHkrewEsBO8+LMCgPnCHt0fCjFYani1JKvHrXkjePWEWD7o/xh/Bw7VS9lfO/t6MwExB9zuvpsTZFEKMrqp80koOl43bGME4LLAqI1UbIYXnh+KklmPOWI3cgy+UcqPuLkPKeTQwGUBWjmcn4e6l3Xxgbja2zSgijToIRwDod7iUOJCXpjD/7r6yEVPdjsX/C/3EWFG0w06lnXw4okxw3F3OewBFzPCeDrJJ71Js5ZpMuVXEk4=
  skip_cleanup: true
