language: node_js
node_js:
  - 6
branches:
  only:
    - master

install:
  - npm install

script:
  - cd functions
  - npm run lint
  - npm run test
  - cd ..

deploy:
  provider: firebase
  token:
    secure: 'bxMHUbwtiGYUSMzDy16tTrMIU4dLeliT2Nnm/OBc7emjfU22R5knP8AhPA0FPO5jTyYbpTm0n7LcKugTPamIlnlxWMd26dOnyySUNmy9R89KtNiNUrzag9o6cd5IuVJwOrddBfBLsHoFAxHWlfE/bzKurj6a8bqKeUJApgHi/RaPPt4hGW9Jw7jm7j5nfq2dafpYYkaxxoDfSgU+dg1rb1k/GWdOgAFvq/LSDMeSpo5NDUQ1k5GNrEi0yOe5WeruyNZZ2OMncKPoQdksPvfQ+6RshYYaEV3FN6equbYgs3c6oGl/PEljzF2/xpL1LTWajbnp1awu85Ui1vzYtX4UkTXpEQxZwXkcdDuSHgOjsKWRxuK/Fl7DdqtLB2ESbNRjwBGJjOm9J2bzeRTSLvRg9QB1P5k0ODOPU7ApIwYaDwaHh6QlVHWe6rYINkOUwGY05zPm9/lMQJf2jslSKCfyCSbnlcnIlNWfZcoUlc2V8WQE0z7YkalSXliAzP+oHYhRqUetQbv1Af+w6CMzt4zgpwZLRlLaRQNK7gvoDqvVyHW8ExM4xxv0zu6FiIfTB6APTbe0O8iOmSGx6mwf+///P3OF8lFm+gv86OHe3QuA1Jyx+T+8Qla+1a76rJILicqqkqPdE/p4gOJVPMOlzcKbZMy7hielVF5HQU8UUHTJuI0='
  skip_cleanup: true
