language: node_js
node_js:
  - 6
branches:
  only:
    - master
script:
  - npm install
  - cd functions
  - npm run lint
  - npm run test
  - cd ..

deploy:
  provider: firebase
  token:
    secure: 'vZwe8ef2owy9af2ZUZglQ5PzXcCPnhw7auFLPZddkvpEyToyUiBLBOnjzz7CFgdy+eL2Mv/KqXO0tsyiBHbif5YW0962WQynVcg4ASGwfTN/p0JJBbzre7n2mvQwCBwO/dPFfDu6wJaqJVL4gi4yoE000rPOWu2vqd8mpnSpgKFmfwloqXQBqbsWupzBr4Dah4t4OikR+dmIVsUfKyaj0DPFOBlF8v5MUCyh9gSc1INbk3yRERAfhL+Ne8DuSUFkMo6GTxd9DuJizdAP5h5iUnvZtXqS5xjHs9NCNl0IASrSjbTC+gFiB8B7YY3Zbc+D1uM4jg8/NfLvQe+4BoDZRQ8u5ztC82KR6hxOw8gJxE3q6YMVSziDVpmNg3skRIiEpG1e7KHm9P1C9ffSQdpPX9PNfy2oaVjRNlq1yn28Fc3KijB0E2HSJUIdJ5oCRXkymwIa6HD00LL0r9UsqgCmt61QatcT522FSogm7XiUhNN8k29xbll3J/FdmXH/lBWQib9Pt90JVwIBWyKLx7eevooi5MkDqwom6HHqCV5llb174yOAk1c4oWwd1hYS0ejp+po+nPgFvR+3w49aNvd3lI//KWKJ0MTinWe8k8AFJ6s/l4KiAObsldmP6hOjcuzkOY+5n6QIi6nohwx+gsmHYlcWt/XGgPufVstyHUMSPH0='
  skip_cleanup: true
