language: node_js
node_js:
  - 6
branches:
  only:
    - master
before_install:
  - cd functions
install:
  - npm install
after_install:
  - cd ..
before_script:
  - cd functions
after_script:
  - cd ..
script:
  - npm run lint
  - npm run test
deploy:
  provider: firebase
  token:
    secure: 'Ul4nibQ1PeUqHVbQ6qUptcnkIUzK64SP6Rq8oVzZugL/HPm+njHu2WfO0f1xfiZquPfcuBVsXx/0kdJuTo/fLRGw03UUD5oFV2UNs+ZhtlxIK6K6fKvxCzxG56iWyhT8CpbPsB4aijbrXd+R1HGtyv0aWWdZCkVl02qTpD0mRwhmm6zZDGP5rz68KD0UYloTwlKaNJayxdQV5HWSdRBUksr0z9N85LsuHgS80IQYLjzTIYN3ibLN1nucFEdF7Kqa9Zu14LqFXz3EjJnO8VlFMhLm2bCMl9wT53kThYUZWUogkfvQ4QoK3dxbZ7vPNEHmisC6ZLovYBe4uHsJ81RPd5sALBK27T0vx0KGW2b4mRWlhhKJ1VFgVOOVy+7F870p4rAx7v/CsoN0k5Hgqe6in/joOHZ38HqRnkc/8L7uPSQnK692TXoJaa1vtXnikku16Rvg0J7HorQXy3qwlY5pOHedcegZANoqoSb/MPGy25BWrEqS0x29T5bwVbreGdh7EF0Sgt52Z4yMQ3/fVcsKxuSU4C8w4QHyiXvqY1wRB9XxLiuVTOtUe73rYw8MpuBldL+35ZqjH5+a8ZUFkYI7TSKX0sY9YzHcwlQy9ou1R15+PvQAul9kvDG/NXk5iZxoDErFqXkkqKG9KwXWFia/VPJWkbLz31Lv3KlnnoxmjDQ='
  skip_cleanup: true
