language: node_js
node_js:
  - 6
  - 8
branches:
  only:
    - master
    - next

script:
  - cd functions
  - npm install
  - npm run lint
  - cd ..

deploy:
  provider: firebase
  token:
 secure: "qaZIdF1dMZWz+LSNyVnPf/JY69/IlFxA5+VA+GYwumrtuHnP+pyD4qjQ8mUL7bWKRx1KWYdgj/PrnXglwDnQF11sR67GJE3xhySjCM0/7bONrmSrFAuwBpemOx0Prk4g5FxEgfbbTZTjCBh+3XYc6/MuR9F0i+SDoHOEldRld0kOwLfEr28EIhuJlchFRZ1X7vpgDR25D8isT56Z0wY/76U9NlKTWlzdtV300Xh7J1EyI7nQZDHoyNmJN/RvG5am+QFwBpZ1xDIJDV6T3K5PySXlrQJInWRCK1T9wRGYSxjgEiFXdsUc7eJxqLRYeMizmLEvr/CL/OPbT1Xn8xcWlZXHBXE+M6If+Gp2B5fhLx/3WTV3LXM7QgfRUbj+bQWsdwpBUa/b9Djp70uW4HKHMdARuY3htPzc3bg2cf8JiMMkdzGNEtE9Sy+xrxKOECc8YjifSrwaqVU7QURibnkU9lb56GqlYT1RTsH1gB7gIerAAYQidSP6tl91ZFfYzEug1uwUU/5gmnLLOox0D8QmJ6oB56d4s343ldoYEPCeoakSU6yQ2xetLShvXBxxVic9cy/Tl0a0uCkDcXHHVDjPERZ0F8Ssh1v+pKvHdIpMK0Pc0EOT4nw7LXQSTo1Gss7ov3o58d56R8Lv+UyUEJwZ25ghQwWD9GyK/CzhOtje0xM="
 skip_cleanup: true
